version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Services/Aries.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - aries-network

  ui:
    build:
      context: .
      dockerfile: src/UI/Aries.Contabilidad/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - aries-network

networks:
  aries-network:
    driver: bridge 