services:
  api:
    image: kenaguilar7/ariesv2-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile.ui
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    driver: bridge 